language: python

cache: pip

env:
  matrix:
    - ELASTIC_LINK=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.6/elasticsearch-2.4.6.deb
#    - ELASTIC_LINK=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.tar.gz

before_install:
  - curl ${ELASTIC_LINK} -o elasticsearch.deb #&& sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch start
  - sudo systemctl start elasticsearch

before_script:
   - sleep 10
   - curl http://localhost:9200/
   - curl http://localhost:9200/_cluster/health

script:
  - nosetests
  - flake8
